// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logger} from '../models';

export function GetLogs():Promise<Array<logger.Log>>;

export function GetServiceStatus():Promise<string>;

export function StartServices():Promise<string>;

export function StopServices():Promise<string>;
