// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function StartServices() {
  return window['go']['main']['App']['StartServices']();
}

export function StopServices() {
  return window['go']['main']['App']['StopServices']();
}
